# Generated by Django 6.0.5 on 2026-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_alter_property_image_alter_property_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Файл картинки новости с компьютера.', upload_to='articles/', verbose_name='загрузить файл картинки'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Файл логотипа компании с компьютера.', upload_to='company/', verbose_name='загрузить файл логотипа'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Файл фотографии сотрудника с компьютера.', upload_to='employees/', verbose_name='загрузить файл фото'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на картинку, если файл не загружен.', verbose_name='ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на логотип, если файл не загружен.', verbose_name='ссылка на логотип'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на фото, если файл не загружен.', verbose_name='ссылка на фото'),
        ),
    ]
