# Generated by Django 6.0.5 on 2026-05-20 16:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import realty.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='удобство')),
            ],
            options={
                'verbose_name': 'удобство',
                'verbose_name_plural': 'удобства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('summary', models.CharField(max_length=255, verbose_name='краткое содержание')),
                ('body', models.TextField(verbose_name='текст статьи')),
                ('image_url', models.URLField(blank=True, verbose_name='картинка')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='категория')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('logo_url', models.URLField(blank=True, verbose_name='логотип')),
                ('video_url', models.URLField(blank=True, verbose_name='видео')),
            ],
            options={
                'verbose_name': 'информация о компании',
                'verbose_name_plural': 'информация о компании',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('question', models.CharField(max_length=255, verbose_name='вопрос')),
                ('answer', models.TextField(verbose_name='ответ')),
                ('added_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'термин/вопрос',
                'verbose_name_plural': 'словарь терминов',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('birth_date', models.DateField(validators=[realty.models.validate_adult], verbose_name='дата рождения')),
                ('phone', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +375 (29) XXX-XX-XX', regex='^\\+375 \\((29|25|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'владелец',
                'verbose_name_plural': 'владельцы',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=160, verbose_name='вакансия')),
                ('description', models.TextField(verbose_name='описание')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='зарплата до')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('birth_date', models.DateField(validators=[realty.models.validate_adult], verbose_name='дата рождения')),
                ('phone', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +375 (29) XXX-XX-XX', regex='^\\+375 \\((29|25|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('title', models.CharField(max_length=150, verbose_name='событие')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='realty.companyinfo', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'этап истории',
                'verbose_name_plural': 'история компании',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='поле')),
                ('value', models.CharField(max_length=255, verbose_name='значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='realty.companyinfo', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'реквизит',
                'verbose_name_plural': 'реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('first_name', models.CharField(max_length=80, verbose_name='имя')),
                ('last_name', models.CharField(max_length=80, verbose_name='фамилия')),
                ('job_title', models.CharField(max_length=120, verbose_name='должность')),
                ('birth_date', models.DateField(validators=[realty.models.validate_adult], verbose_name='дата рождения')),
                ('phone', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +375 (29) XXX-XX-XX', regex='^\\+375 \\((29|25|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('photo_url', models.URLField(blank=True, verbose_name='фото')),
                ('responsibilities', models.TextField(verbose_name='выполняемые работы')),
                ('hire_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата приема')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='код')),
                ('description', models.TextField(verbose_name='описание')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='скидка, %')),
                ('valid_from', models.DateField(verbose_name='действует с')),
                ('valid_to', models.DateField(verbose_name='действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('categories', models.ManyToManyField(blank=True, to='realty.category', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды и купоны',
                'ordering': ['-is_active', 'valid_to'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=180, verbose_name='название')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('city', models.CharField(default='Минск', max_length=80, verbose_name='город')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена, BYN')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='площадь, м2')),
                ('rooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='комнат')),
                ('floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='этаж')),
                ('total_floors', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='этажей')),
                ('description', models.TextField(verbose_name='описание')),
                ('image_url', models.URLField(blank=True, verbose_name='картинка')),
                ('status', models.CharField(choices=[('active', 'В продаже'), ('reserved', 'Зарезервировано'), ('sold', 'Продано'), ('archived', 'Архив')], default='active', max_length=20, verbose_name='статус')),
                ('amenities', models.ManyToManyField(blank=True, to='realty.amenity', verbose_name='удобства')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='realty.employee', verbose_name='сотрудник')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='realty.category', verbose_name='категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='realty.owner', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'объект недвижимости',
                'verbose_name_plural': 'объекты недвижимости',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('text', models.TextField(verbose_name='текст')),
                ('added_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-added_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('sold_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата продажи')),
                ('contract_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата договора')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма сделки, BYN')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='комиссия, %')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='realty.buyer', verbose_name='покупатель')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='realty.employee', verbose_name='сотрудник')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='realty.property', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'ordering': ['-sold_at'],
            },
        ),
    ]
