# Generated by Django 6.0.5 on 2026-05-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите файл с компьютера. Это поле важнее ссылки ниже.', upload_to='properties/', verbose_name='загрузить файл картинки'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, help_text='Можно вставить прямую ссылку на изображение. Если файл не загружен, будет использована эта ссылка.', verbose_name='ссылка на картинку'),
        ),
    ]
