from django.urls import path, re_path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("news/", views.ArticleListView.as_view(), name="article_list"),
    re_path(r"^news/(?P<pk>\d+)/$", views.ArticleDetailView.as_view(), name="article_detail"),
    re_path(r"^news/(?P<pk>\d+)/image.svg$", views.generated_article_image, name="article_generated_image"),
    path("terms/", views.faq_list, name="faq_list"),
    path("contacts/", views.contacts, name="contacts"),
    re_path(r"^employees/(?P<pk>\d+)/photo.svg$", views.generated_employee_photo, name="employee_generated_photo"),
    path("privacy/", views.privacy, name="privacy"),
    path("vacancies/", views.vacancies, name="vacancies"),
    path("promos/", views.promos, name="promos"),
    path("properties/", views.PropertyListView.as_view(), name="property_list"),
    re_path(r"^properties/(?P<pk>\d+)/$", views.PropertyDetailView.as_view(), name="property_detail"),
    re_path(r"^properties/(?P<pk>\d+)/image.svg$", views.generated_property_image, name="property_generated_image"),
    re_path(r"^properties/(?P<pk>\d+)/buy/$", views.property_buy_confirm, name="property_buy_confirm"),
    re_path(r"^properties/(?P<pk>\d+)/buy/confirm/$", views.property_buy, name="property_buy"),
    path("properties/create/", views.PropertyCreateView.as_view(), name="property_create"),
    re_path(r"^properties/(?P<pk>\d+)/edit/$", views.PropertyUpdateView.as_view(), name="property_update"),
    re_path(r"^properties/(?P<pk>\d+)/delete/$", views.PropertyDeleteView.as_view(), name="property_delete"),
    path("sales/", views.SaleListView.as_view(), name="sale_list"),
    path("sales/create/", views.SaleCreateView.as_view(), name="sale_create"),
    re_path(r"^sales/(?P<pk>\d+)/edit/$", views.SaleUpdateView.as_view(), name="sale_update"),
    re_path(r"^sales/(?P<pk>\d+)/delete/$", views.SaleDeleteView.as_view(), name="sale_delete"),
    path("reviews/", views.reviews, name="reviews"),
    path("reviews/create/", views.review_create, name="review_create"),
    path("profile/", views.profile, name="profile"),
    path("register/", views.register, name="register"),
    path("login/", views.RealtyLoginView.as_view(), name="login"),
    path("logout/", views.RealtyLogoutView.as_view(), name="logout"),
    path("statistics/", views.statistics_view, name="statistics"),
    path("time/", views.timezone_view, name="timezone"),
    path("external-services/", views.external_services, name="external_services"),
    path("api/properties/", views.properties_api, name="properties_api"),
]
